import type { Platform } from "../types.js";

/**
 * All SocialCrawl platforms with ACTIVE registry endpoints, derived from the
 * backend registry. Generated by scripts/generate-data.ts — do not hand-edit.
 * Descriptions are maintained in that script.
 *
 * The non-registry `monitors` family lives in ./monitors.ts and is merged in
 * by ../catalog.ts.
 * Source: packages/social-api/src/registry/config.ts
 */
export const PLATFORMS: Platform[] = [
  {
    slug: "web",
    name: "Web Scraping",
    endpointCount: 22,
    social: false,
    description:
      "Web scraping and research — scrape any URL to clean markdown/HTML, web search with optional page content, site mapping, LLM-powered structured extraction, async crawl and batch-scrape jobs, an autonomous web agent, scheduled page monitors with change detection, interactive browser sessions with remote code execution, and document parsing. The stateful routes (jobs, monitors, sessions) span GET/POST/PATCH/DELETE and use `{id}` path templates — set the `method` input to pick a verb and supply the id as a normal parameter.",
  },
  {
    slug: "tiktok",
    name: "TikTok",
    endpointCount: 21,
    social: true,
    category: "major",
    description:
      "Profiles, videos, comments and replies, keyword/hashtag/top/user search, trending feed, audience demographics, followers, following, live streams, songs, video transcripts, on-screen text extraction, profile region lookup, and a one-call full profile dossier (profile + recent posts + computed analytics).",
  },
  {
    slug: "instagram",
    name: "Instagram",
    endpointCount: 33,
    social: true,
    category: "major",
    description:
      "Profiles, posts, reels, comments, story highlights, stories, tagged posts, location feeds, followers, following, similar accounts, post likers, post-reshare stats, one-call reels/posts lists with per-item share counts, account engagement analytics, reels/hashtag/profile/location/music search, username suggestions, trending reels and music, audio reels, embed HTML, and AI-powered media transcripts.",
  },
  {
    slug: "youtube",
    name: "YouTube",
    endpointCount: 28,
    social: true,
    category: "major",
    description:
      "Channels, videos, shorts, comments and replies, video sponsors, playlists and playlist items, community posts, keyword/hashtag/advanced search and autocomplete suggestions, trending videos and shorts, channel live streams, downloadable media files (audio, video, subtitles, thumbnails), batch video/channel/transcript lookups, and video transcripts.",
  },
  {
    slug: "twitter",
    name: "Twitter/X",
    endpointCount: 8,
    social: true,
    category: "major",
    description:
      "Profiles, tweets, communities, community tweets, video transcripts, AI-powered natural-language X search via Grok with citations, and a one-call full profile dossier.",
  },
  {
    slug: "linkedin",
    name: "LinkedIn",
    endpointCount: 44,
    social: true,
    category: "major",
    description:
      "Personal profiles and company pages, posts, reposts, reactions, group and company posts, post comments and replies, people and company-people search, structured profile sub-resources (experiences, educations, skills, honors, certifications, publications, volunteers, recommendations, interests, images, videos), jobs (job search, company jobs, job details), company insights and job counts, groups, location/school/industry search, post transcripts, and the LinkedIn Ad Library (ad details, ad search).",
  },
  {
    slug: "facebook",
    name: "Facebook",
    endpointCount: 23,
    social: true,
    category: "major",
    description:
      "Pages, posts, comments and replies, group posts, photos, reels, one-call reels lists with exact views/likes/comments/shares merged in, events with event details and event search, Marketplace (keyword search, location search, item details), video and ad transcripts, the full Facebook Ad Library (ads, company ads, ad search, company search), and a one-call full profile dossier.",
  },
  {
    slug: "reddit",
    name: "Reddit",
    endpointCount: 8,
    social: true,
    category: "major",
    description:
      "Subreddit posts and details, single post lookup, post comments, keyword search, subreddit search, post video transcripts, and a one-keyword omni-search across all of Reddit with subreddit attribution and top comments inline.",
  },
  {
    slug: "threads",
    name: "Threads",
    endpointCount: 6,
    social: true,
    category: "major",
    description:
      "Profiles, posts, post details, post comments, keyword search, and user search.",
  },
  {
    slug: "pinterest",
    name: "Pinterest",
    endpointCount: 5,
    social: true,
    category: "additional",
    description:
      "Pins, boards, user boards, keyword search, and Pinterest Save-Button counts for any URL (url-stats).",
  },
  {
    slug: "twitch",
    name: "Twitch",
    endpointCount: 4,
    social: true,
    category: "additional",
    description:
      "Streamer profiles, clip details, user videos, and broadcast schedules.",
  },
  {
    slug: "snapchat",
    name: "Snapchat",
    endpointCount: 1,
    social: true,
    category: "additional",
    description:
      "Public user profiles including subscriber count and bio.",
  },
  {
    slug: "truthsocial",
    name: "Truth Social",
    endpointCount: 3,
    social: true,
    category: "additional",
    description:
      "Profiles, user posts, and post details.",
  },
  {
    slug: "kick",
    name: "Kick",
    endpointCount: 1,
    social: true,
    category: "additional",
    description:
      "Clip details including view count, duration, and category.",
  },
  {
    slug: "kwai",
    name: "Kwai",
    endpointCount: 3,
    social: true,
    category: "additional",
    description:
      "Profiles, user posts, and post details from Kwai (Kuaishou's international short-video app).",
  },
  {
    slug: "tiktokshop",
    name: "TikTok Shop",
    endpointCount: 5,
    social: true,
    category: "commerce",
    description:
      "TikTok Shop product details, product reviews, shop product listings, shop search, and creator showcases.",
  },
  {
    slug: "perplexity",
    name: "Perplexity",
    endpointCount: 1,
    social: false,
    category: "utility",
    description:
      "Web research via Perplexity Sonar — returns a grounded answer with cited source URLs.",
  },
  {
    slug: "google",
    name: "Google",
    endpointCount: 10,
    social: true,
    category: "utility",
    description:
      "Google web search, Google Ads Transparency Center (ad details, advertiser search, company ads), Google Business Profile (place info, extended cross-source reviews, owner updates, Q&A), and Google Travel hotels (search + rich hotel details).",
  },
  {
    slug: "amazon",
    name: "Amazon",
    endpointCount: 5,
    social: true,
    description:
      "Product search, full ASIN product details, on-page reviews, buy-box sellers and offers, and Amazon shop/storefront pages — across ~13 Amazon marketplaces via the country parameter.",
  },
  {
    slug: "google_shopping",
    name: "Google Shopping",
    endpointCount: 4,
    social: false,
    category: "commerce",
    description:
      "Google Shopping product search, full product details, reviews aggregated across retailers, and per-seller offers with itemised pricing.",
  },
  {
    slug: "google_news",
    name: "Google News",
    endpointCount: 1,
    social: false,
    category: "utility",
    description:
      "Real-time Google News SERP search — ranked headlines with source, snippet, and timestamp for any query.",
  },
  {
    slug: "google_finance",
    name: "Google Finance",
    endpointCount: 3,
    social: false,
    category: "utility",
    description:
      "Financial-instrument data — full quotes, a markets overview (indices + top movers), and ticker search by name.",
  },
  {
    slug: "google_trends",
    name: "Google Trends",
    endpointCount: 2,
    social: false,
    description:
      "Google Trends interest data — explore interest-over-time and regional interest for one or more keywords, and surface rising related queries for a seed keyword, with optional location, timeframe, and category filters.",
  },
  {
    slug: "trustpilot",
    name: "Trustpilot",
    endpointCount: 2,
    social: false,
    category: "commerce",
    description:
      "Trustpilot business search and company reviews — brand-reputation data keyed by company domain (shipping, refunds, support sentiment). For product reviews use amazon/reviews or google_shopping/reviews.",
  },
  {
    slug: "google_play",
    name: "Google Play",
    endpointCount: 9,
    social: false,
    description:
      "Google Play app search, full app details, app reviews with developer replies, store charts (top free/paid/grossing), a filterable app listings database, and categories/locations/languages reference data.",
  },
  {
    slug: "app_store",
    name: "Apple App Store",
    endpointCount: 9,
    social: false,
    description:
      "Apple App Store app search, full app details, app reviews, store charts (top free/paid/grossing for iPhone and iPad), a filterable app listings database, and categories/locations/languages reference data.",
  },
  {
    slug: "tripadvisor",
    name: "Tripadvisor",
    endpointCount: 2,
    social: false,
    category: "commerce",
    description:
      "Place and business search (restaurants, hotels, attractions) and traveler reviews with owner replies, review images, and cross-language auto-translation metadata.",
  },
  {
    slug: "walmart",
    name: "Walmart",
    endpointCount: 5,
    social: false,
    category: "commerce",
    description:
      "Walmart product details, product reviews, keyword search, category browse, and every seller offering a given product.",
  },
  {
    slug: "target",
    name: "Target",
    endpointCount: 5,
    social: false,
    category: "commerce",
    description:
      "Target product details by TCIN, product reviews, category browse, the full category taxonomy, and store lookup near a location.",
  },
  {
    slug: "home_depot",
    name: "Home Depot",
    endpointCount: 2,
    social: false,
    category: "commerce",
    description:
      "Home Depot product details by item id or URL, plus product reviews.",
  },
  {
    slug: "ebay",
    name: "eBay",
    endpointCount: 2,
    social: false,
    category: "commerce",
    description:
      "eBay listing search and full listing details by item id.",
  },
  {
    slug: "utility",
    name: "Utility",
    endpointCount: 4,
    social: true,
    category: "utility",
    description:
      "The API's own developer-experience surface, and the best place to start — all free (0 credits). `quickstart` returns auth, the response envelope, the credit model, the full error taxonomy, rate limits and a working first call in one response. `endpoints` is the machine-readable catalog of everything callable. `endpoint` is the complete usage guide for any single endpoint, with a copy-paste curl and an example response. `llms` is the AI-agent context corpus, so an agent can bootstrap itself in one call instead of scraping docs. All four are generated from the live registry at request time, so they never drift from what is actually callable.",
  },
  {
    slug: "linktree",
    name: "Linktree",
    endpointCount: 1,
    social: true,
    category: "linkPages",
    description:
      "Linktree link-in-bio pages including display name, bio, avatar, and link list.",
  },
  {
    slug: "linkbio",
    name: "LinkBio",
    endpointCount: 1,
    social: true,
    category: "linkPages",
    description:
      "Linkbio link-in-bio pages including display name, bio, avatar, and link list.",
  },
  {
    slug: "linkme",
    name: "LinkMe",
    endpointCount: 1,
    social: true,
    description:
      "Linkme link-in-bio pages including display name, bio, avatar, and link list.",
  },
  {
    slug: "komi",
    name: "Komi",
    endpointCount: 1,
    social: true,
    category: "linkPages",
    description:
      "Komi link-in-bio pages including display name, bio, avatar, and link list.",
  },
  {
    slug: "pillar",
    name: "Pillar",
    endpointCount: 1,
    social: true,
    category: "linkPages",
    description:
      "Pillar link-in-bio pages including display name, bio, avatar, and link list.",
  },
  {
    slug: "polymarket",
    name: "Polymarket",
    endpointCount: 1,
    social: false,
    category: "utility",
    description:
      "Prediction-market research — a server-side fan-out that expands a topic across multiple queries and ranks the merged Polymarket events.",
  },
  {
    slug: "hackernews",
    name: "Hacker News",
    endpointCount: 4,
    social: false,
    category: "utility",
    description:
      "Story search, story details, story comment trees, and user profiles.",
  },
  {
    slug: "github",
    name: "GitHub",
    endpointCount: 12,
    social: false,
    category: "utility",
    description:
      "Users, repositories, user repos, READMEs, releases, issues, pull requests, issue/PR comments, issue/PR search, and composite repo top-issues/dossier + user profile-velocity reports.",
  },
  {
    slug: "tavily",
    name: "Tavily",
    endpointCount: 4,
    social: false,
    category: "utility",
    description:
      "Web search with optional LLM-synthesised answer, content extraction from URLs, lightweight sitemap discovery, and full multi-page crawl.",
  },
  {
    slug: "naver",
    name: "Naver",
    endpointCount: 14,
    social: true,
    category: "utility",
    description:
      "Korea's #1 search portal — 8 search corpora (blog, news, encyclopedia, cafe article, Q&A (KiN), local places, image, and web search), Korean query errata correction and adult-term detection, Data Lab search-volume trends and Shopping click-insight by category and keyword, plus a cross-corpus brief that fans one query across the main corpora with an optional digest.",
  },
  {
    slug: "rumble",
    name: "Rumble",
    endpointCount: 5,
    social: true,
    category: "additional",
    description:
      "Video search, channel videos, video details, video comments, and video transcripts.",
  },
  {
    slug: "bluesky",
    name: "Bluesky",
    endpointCount: 3,
    social: true,
    category: "additional",
    description:
      "Profiles, user posts, and post details from the AT Protocol social network.",
  },
  {
    slug: "spotify",
    name: "Spotify",
    endpointCount: 6,
    social: true,
    category: "additional",
    description:
      "Artists, tracks, albums, podcasts, podcast episodes, and search across the Spotify catalog.",
  },
  {
    slug: "search",
    name: "Universal Search",
    endpointCount: 3,
    social: false,
    category: "utility",
    description:
      "Meta-search across 14 platforms in a single call (up to 17 sources in hashtag mode) — LLM-planned, RRF-fused, LLM-reranked and clustered — plus a fused forum search across Reddit, Hacker News and Korean forums with top comments inline, and a planned multi-country news search that localizes one query across Google News editions.",
  },
  {
    slug: "prism",
    name: "Prism",
    endpointCount: 33,
    social: false,
    description:
      "Cross-platform composite intelligence — server-side recipes that fan out across many platforms and fold the legs into one unified report. Universal URL lookup, full comment harvesting, brand-mention and consumer-demand nowcasts, AI share-of-voice / GEO monitoring, crisis radar and post-mortems, cross-source reputation, share-of-voice, creator vetting, multi-engine AI consensus answers, and video/app/product intelligence. Each composite emits a per-leg transparency array; pricing is flat or metered per recipe — run action \"List pricing\" for the exact band.",
  },
  {
    slug: "content_analysis",
    name: "Content Analysis",
    endpointCount: 10,
    social: false,
    description:
      "Cross-web brand-mention search and 6-axis sentiment intelligence over news, blogs, ecommerce, and message boards — paginated mention feeds, sentiment/summary aggregates, rating distributions, phrase and category trends, plus languages/locations/categories/filters reference data.",
  },
];
