import type { Platform } from "../types.js";

/**
 * All SocialCrawl platforms with ACTIVE registry endpoints, derived from the
 * backend registry. Generated by scripts/generate-data.ts — do not hand-edit.
 * Descriptions are maintained in that script.
 *
 * The non-registry `monitors` family lives in ./monitors.ts and is merged in
 * by ../catalog.ts.
 * Source: packages/social-api/src/registry/config.ts
 */
export const PLATFORMS: Platform[] = [
  {
    slug: "web",
    name: "Web Scraping",
    endpointCount: 22,
    social: false,
    description:
      "Web scraping and research — scrape any URL to clean markdown/HTML, web search with optional page content, site mapping, LLM-powered structured extraction, async crawl and batch-scrape jobs, an autonomous web agent, scheduled page monitors with change detection, interactive browser sessions with remote code execution, and document parsing. The stateful routes (jobs, monitors, sessions) span GET/POST/PATCH/DELETE and use `{id}` path templates — set the `method` input to pick a verb and supply the id as a normal parameter.",
  },
  {
    slug: "tiktok",
    name: "TikTok",
    endpointCount: 36,
    social: true,
    category: "major",
    description:
      "Profiles, videos, comments and replies, keyword/hashtag/top/user/sound search and autocomplete suggestions, trending feed, hashtag details, audience demographics, followers, following, liked videos, live streams, songs and song feeds, playlists, collections, effects and effect feeds, place-tagged videos, the TikTok Ad Library (ad search + ad details), video transcripts, on-screen text extraction, profile region lookup, and a one-call full profile dossier (profile + recent posts + computed analytics).",
  },
  {
    slug: "instagram",
    name: "Instagram",
    endpointCount: 37,
    social: true,
    category: "major",
    description:
      "Profiles, account transparency details, posts, reels, comments and comment replies, story highlights, stories and single-story download, tagged posts, location feeds, followers, following, similar accounts, post likers, post-reshare stats, one-call reels/posts lists with per-item share counts, account engagement analytics, unified/popular/reels/hashtag/profile/location/music search, username suggestions, trending reels and music, audio reels, embed HTML, and AI-powered media transcripts.",
  },
  {
    slug: "youtube",
    name: "YouTube",
    endpointCount: 29,
    social: true,
    category: "major",
    description:
      "Channels, channel contact email and country, videos, shorts, comments and replies, video sponsors, playlists and playlist items, community posts, keyword/hashtag/advanced search and autocomplete suggestions, trending videos and shorts, channel live streams, downloadable media files (audio, video, subtitles, thumbnails), batch video/channel/transcript lookups, and video transcripts.",
  },
  {
    slug: "twitter",
    name: "Twitter/X",
    endpointCount: 15,
    social: true,
    category: "major",
    description:
      "Profiles, tweets, tweet replies and retweeters, user media, followers, following, tweet and user search, communities, community tweets, video transcripts, AI-powered natural-language X search via Grok with citations, and a one-call full profile dossier.",
  },
  {
    slug: "linkedin",
    name: "LinkedIn",
    endpointCount: 45,
    social: true,
    category: "major",
    description:
      "Personal profiles and company pages, posts, a metered complete post-history archive, reposts, reactions, group and company posts, post comments and replies, people and company-people search, structured profile sub-resources (experiences, educations, skills, honors, certifications, publications, volunteers, recommendations, interests, images, videos, comments), jobs (job search, company jobs, job details), company insights and job counts, groups, location/school/industry search, public post search, post transcripts, and the LinkedIn Ad Library (ad details, ad search).",
  },
  {
    slug: "facebook",
    name: "Facebook",
    endpointCount: 24,
    social: true,
    category: "major",
    description:
      "Pages, groups and group posts, posts, comments and replies, photos, reels, one-call reels lists with exact views/likes/comments/shares merged in, events with event details and event search, Marketplace (keyword search, location search, item details), video and ad transcripts, the full Facebook Ad Library (ads, company ads, ad search, company search), and a one-call full profile dossier.",
  },
  {
    slug: "reddit",
    name: "Reddit",
    endpointCount: 14,
    social: true,
    category: "major",
    description:
      "Subreddit posts and details, user profiles with their post and comment history, single post lookup, post comments, post/comment/media keyword search, in-subreddit search, subreddit discovery by topic, post video transcripts, and a one-keyword omni-search across all of Reddit with subreddit attribution and top comments inline.",
  },
  {
    slug: "threads",
    name: "Threads",
    endpointCount: 6,
    social: true,
    category: "major",
    description:
      "Profiles, posts, post details, post comments, keyword search, and user search.",
  },
  {
    slug: "pinterest",
    name: "Pinterest",
    endpointCount: 5,
    social: true,
    category: "additional",
    description:
      "Pins, boards, user boards, keyword search, and Pinterest Save-Button counts for any URL (url-stats).",
  },
  {
    slug: "twitch",
    name: "Twitch",
    endpointCount: 4,
    social: true,
    category: "additional",
    description:
      "Streamer profiles, clip details, user videos, and broadcast schedules.",
  },
  {
    slug: "snapchat",
    name: "Snapchat",
    endpointCount: 2,
    social: true,
    category: "additional",
    description:
      "Public user profiles including subscriber count and bio, plus comments on a Spotlight clip.",
  },
  {
    slug: "truthsocial",
    name: "Truth Social",
    endpointCount: 3,
    social: true,
    category: "additional",
    description:
      "Profiles, user posts, and post details.",
  },
  {
    slug: "telegram",
    name: "Telegram",
    endpointCount: 3,
    social: true,
    category: "additional",
    description:
      "Public Telegram channels and groups — channel profiles with exact subscriber counts, paginated channel post feeds, and single posts by t.me URL, each with text, publish time, view count, the per-emoji reaction breakdown, and direct media URLs.",
  },
  {
    slug: "kick",
    name: "Kick",
    endpointCount: 1,
    social: true,
    category: "additional",
    description:
      "Clip details including view count, duration, and category.",
  },
  {
    slug: "kwai",
    name: "Kwai",
    endpointCount: 3,
    social: true,
    category: "additional",
    description:
      "Profiles, user posts, and post details from Kwai (Kuaishou's international short-video app).",
  },
  {
    slug: "tiktokshop",
    name: "TikTok Shop",
    endpointCount: 5,
    social: true,
    category: "commerce",
    description:
      "TikTok Shop product details, product reviews, shop product listings, shop search, and creator showcases.",
  },
  {
    slug: "perplexity",
    name: "Perplexity",
    endpointCount: 1,
    social: false,
    category: "utility",
    description:
      "Web research via Perplexity Sonar — returns a grounded answer with cited source URLs.",
  },
  {
    slug: "google",
    name: "Google",
    endpointCount: 10,
    social: true,
    category: "utility",
    description:
      "Google web search, Google Ads Transparency Center (ad details, advertiser search, company ads), Google Business Profile (place info, extended cross-source reviews, owner updates, Q&A), and Google Travel hotels (search + rich hotel details).",
  },
  {
    slug: "amazon",
    name: "Amazon",
    endpointCount: 8,
    social: true,
    description:
      "Product search, full ASIN product details, on-page reviews, buy-box sellers and offers, seller profiles, Best Sellers by category, current deals, and Amazon shop/storefront pages — across ~13 Amazon marketplaces via the country parameter.",
  },
  {
    slug: "google_shopping",
    name: "Google Shopping",
    endpointCount: 5,
    social: false,
    category: "commerce",
    description:
      "Google Shopping product search, full product details, reviews aggregated across retailers, per-seller offers with itemised pricing, and product price history.",
  },
  {
    slug: "google_news",
    name: "Google News",
    endpointCount: 1,
    social: false,
    category: "utility",
    description:
      "Real-time Google News SERP search — ranked headlines with source, snippet, and timestamp for any query.",
  },
  {
    slug: "finance",
    name: "Finance",
    endpointCount: 7,
    social: false,
    category: "utility",
    description:
      "Financial-instrument data — full quotes for stocks, ETFs, indices, forex and crypto, ticker search by name, a markets overview (regional indices plus the day's movers), instrument news, daily price history, company financial statements (income, balance sheet, cash flow), and options chains.",
  },
  {
    slug: "google_trends",
    name: "Google Trends",
    endpointCount: 3,
    social: false,
    description:
      "Google Trends interest data — explore interest-over-time and regional interest for one or more keywords, and surface rising related queries for a seed keyword, with optional location, timeframe, and category filters.",
  },
  {
    slug: "trustpilot",
    name: "Trustpilot",
    endpointCount: 2,
    social: false,
    category: "commerce",
    description:
      "Trustpilot business search and company reviews — brand-reputation data keyed by company domain (shipping, refunds, support sentiment). For product reviews use amazon/reviews or google_shopping/reviews.",
  },
  {
    slug: "g2",
    name: "G2",
    endpointCount: 7,
    social: false,
    category: "commerce",
    description:
      "G2 software reviews — product pages by slug or URL, product reviews, category product listings and the full category index, vendor (seller) profiles and their product catalogues, and a product-URL index for bulk discovery.",
  },
  {
    slug: "google_play",
    name: "Google Play",
    endpointCount: 9,
    social: false,
    description:
      "Google Play app search, full app details, app reviews with developer replies, store charts (top free/paid/grossing), a filterable app listings database, and categories/locations/languages reference data.",
  },
  {
    slug: "app_store",
    name: "Apple App Store",
    endpointCount: 9,
    social: false,
    description:
      "Apple App Store app search, full app details, app reviews, store charts (top free/paid/grossing for iPhone and iPad), a filterable app listings database, and categories/locations/languages reference data.",
  },
  {
    slug: "tripadvisor",
    name: "Tripadvisor",
    endpointCount: 16,
    social: false,
    category: "commerce",
    description:
      "The full Tripadvisor travel surface — cross-type place and business search with autocomplete, single places by URL, and dedicated hotel, restaurant, attraction and cruise search plus per-entity detail pages and their traveler reviews (with owner replies, review images, and cross-language auto-translation metadata), plus the experience types available in a destination.",
  },
  {
    slug: "walmart",
    name: "Walmart",
    endpointCount: 5,
    social: false,
    category: "commerce",
    description:
      "Walmart product details, product reviews, keyword search, category browse, and every seller offering a given product.",
  },
  {
    slug: "target",
    name: "Target",
    endpointCount: 5,
    social: false,
    category: "commerce",
    description:
      "Target product details by TCIN, product reviews, category browse, the full category taxonomy, and store lookup near a location.",
  },
  {
    slug: "wayfair",
    name: "Wayfair",
    endpointCount: 3,
    social: false,
    category: "commerce",
    description:
      "Wayfair keyword product search, product details by SKU, and product reviews.",
  },
  {
    slug: "home_depot",
    name: "Home Depot",
    endpointCount: 4,
    social: false,
    category: "commerce",
    description:
      "Home Depot keyword product search, product details by item id or URL, product reviews, and store lookup near a ZIP code.",
  },
  {
    slug: "ebay",
    name: "eBay",
    endpointCount: 2,
    social: false,
    category: "commerce",
    description:
      "eBay listing search and full listing details by item id.",
  },
  {
    slug: "etsy",
    name: "Etsy",
    endpointCount: 4,
    social: false,
    category: "commerce",
    description:
      "Etsy listings by id or URL, shop product listings, similar-listing recommendations, and search suggestions.",
  },
  {
    slug: "sephora",
    name: "Sephora",
    endpointCount: 11,
    social: false,
    category: "commerce",
    description:
      "Sephora product details, reviews, keyword search and search suggestions, category browse with the category tree, brand listings and per-brand products, store lookup near a coordinate, and in-store SKU availability.",
  },
  {
    slug: "aliexpress",
    name: "AliExpress",
    endpointCount: 9,
    social: false,
    category: "commerce",
    description:
      "AliExpress product details, keyword search, similar products, reviews, per-SKU shipping options and costs, hot-product and promotion feeds, the category tree, and the list of featured promotions.",
  },
  {
    slug: "hm",
    name: "H&M",
    endpointCount: 6,
    social: false,
    category: "commerce",
    description:
      "H&M keyword product search and search suggestions, the category tree, per-country store lists, the countries/languages reference, and the supplier-and-factory disclosure behind a product.",
  },
  {
    slug: "kohls",
    name: "Kohl's",
    endpointCount: 5,
    social: false,
    category: "commerce",
    description:
      "Kohl's keyword product search, product reviews, customer questions and answers, store lookup near a coordinate, and the category tree.",
  },
  {
    slug: "klarna",
    name: "Klarna",
    endpointCount: 18,
    social: false,
    category: "commerce",
    description:
      "Klarna's shopping comparison surface — product details, merchant offers for a product, keyword search and suggestions, user and professional reviews plus review-score overviews, price history, side-by-side product comparison, category browse with the full category tree, per-category filters, popular keywords and buying guides, and store listings with their products and filters.",
  },
  {
    slug: "gumtree",
    name: "Gumtree",
    endpointCount: 11,
    social: false,
    category: "commerce",
    description:
      "Gumtree UK classifieds — keyword listing search, single ads by id or URL, similar listings, seller profiles and their active ads, search suggestions, trending searches, the category tree, per-category filters, and location autocomplete and nearest-location lookup.",
  },
  {
    slug: "yelp",
    name: "Yelp",
    endpointCount: 5,
    social: false,
    category: "commerce",
    description:
      "Yelp business lookup by encid, business reviews, business search in both compact and full-card form, and search suggestions.",
  },
  {
    slug: "utility",
    name: "Utility",
    endpointCount: 4,
    social: true,
    category: "utility",
    description:
      "The API's own developer-experience surface, and the best place to start — all free (0 credits). `quickstart` returns auth, the response envelope, the credit model, the full error taxonomy, rate limits and a working first call in one response. `endpoints` is the machine-readable catalog of everything callable. `endpoint` is the complete usage guide for any single endpoint, with a copy-paste curl and an example response. `llms` is the AI-agent context corpus, so an agent can bootstrap itself in one call instead of scraping docs. All four are generated from the live registry at request time, so they never drift from what is actually callable.",
  },
  {
    slug: "linktree",
    name: "Linktree",
    endpointCount: 1,
    social: true,
    category: "linkPages",
    description:
      "Linktree link-in-bio pages including display name, bio, avatar, and link list.",
  },
  {
    slug: "linkbio",
    name: "LinkBio",
    endpointCount: 1,
    social: true,
    category: "linkPages",
    description:
      "Linkbio link-in-bio pages including display name, bio, avatar, and link list.",
  },
  {
    slug: "linkme",
    name: "LinkMe",
    endpointCount: 1,
    social: true,
    description:
      "Linkme link-in-bio pages including display name, bio, avatar, and link list.",
  },
  {
    slug: "komi",
    name: "Komi",
    endpointCount: 1,
    social: true,
    category: "linkPages",
    description:
      "Komi link-in-bio pages including display name, bio, avatar, and link list.",
  },
  {
    slug: "pillar",
    name: "Pillar",
    endpointCount: 1,
    social: true,
    category: "linkPages",
    description:
      "Pillar link-in-bio pages including display name, bio, avatar, and link list.",
  },
  {
    slug: "polymarket",
    name: "Polymarket",
    endpointCount: 1,
    social: false,
    category: "utility",
    description:
      "Prediction-market research — a server-side fan-out that expands a topic across multiple queries and ranks the merged Polymarket events.",
  },
  {
    slug: "hackernews",
    name: "Hacker News",
    endpointCount: 4,
    social: false,
    category: "utility",
    description:
      "Story search, story details, story comment trees, and user profiles.",
  },
  {
    slug: "quora",
    name: "Quora",
    endpointCount: 7,
    social: true,
    category: "additional",
    description:
      "Question search, single questions with their answers, answer search, Space post search, profile search, Space search, and topic search across Quora.",
  },
  {
    slug: "douyin",
    name: "Douyin",
    endpointCount: 8,
    social: true,
    category: "additional",
    description:
      "China's Douyin (抖音) — creator profiles, their video feeds, single videos, video comments and comment replies, keyword video search, creator search, and the hot-search trending board. Most of the surface is metered per row returned, so quote the band from action \"List pricing\" before sizing a crawl.",
  },
  {
    slug: "github",
    name: "GitHub",
    endpointCount: 12,
    social: false,
    category: "utility",
    description:
      "Users, repositories, user repos, READMEs, releases, issues, pull requests, issue/PR comments, issue/PR search, and composite repo top-issues/dossier + user profile-velocity reports.",
  },
  {
    slug: "tavily",
    name: "Tavily",
    endpointCount: 4,
    social: false,
    category: "utility",
    description:
      "Web search with optional LLM-synthesised answer, content extraction from URLs, lightweight sitemap discovery, and full multi-page crawl.",
  },
  {
    slug: "naver",
    name: "Naver",
    endpointCount: 14,
    social: true,
    category: "utility",
    description:
      "Korea's #1 search portal — 8 search corpora (blog, news, encyclopedia, cafe article, Q&A (KiN), local places, image, and web search), Korean query errata correction and adult-term detection, Data Lab search-volume trends and Shopping click-insight by category and keyword, plus a cross-corpus brief that fans one query across the main corpora with an optional digest.",
  },
  {
    slug: "rumble",
    name: "Rumble",
    endpointCount: 5,
    social: true,
    category: "additional",
    description:
      "Video search, channel videos, video details, video comments, and video transcripts.",
  },
  {
    slug: "bluesky",
    name: "Bluesky",
    endpointCount: 3,
    social: true,
    category: "additional",
    description:
      "Profiles, user posts, and post details from the AT Protocol social network.",
  },
  {
    slug: "spotify",
    name: "Spotify",
    endpointCount: 6,
    social: true,
    category: "additional",
    description:
      "Artists, tracks, albums, podcasts, podcast episodes, and search across the Spotify catalog.",
  },
  {
    slug: "apple_music",
    name: "Apple Music",
    endpointCount: 4,
    social: true,
    category: "additional",
    description:
      "Catalog search plus artists, albums, and tracks from Apple Music.",
  },
  {
    slug: "search",
    name: "Universal Search",
    endpointCount: 4,
    social: false,
    category: "utility",
    description:
      "Meta-search across 14 platforms in a single call (up to 17 sources in hashtag mode) — LLM-planned, RRF-fused, LLM-reranked and clustered — plus a fused forum search across Reddit, Hacker News and Korean forums with top comments inline, creator discovery fused across TikTok, Threads and Instagram, and a multi-country news search that localizes one query across two independent news indexes.",
  },
  {
    slug: "prism",
    name: "Prism",
    endpointCount: 33,
    social: false,
    description:
      "Cross-platform composite intelligence — server-side recipes that fan out across many platforms and fold the legs into one unified report. Universal URL lookup, full comment harvesting, brand-mention and consumer-demand nowcasts, AI share-of-voice / GEO monitoring, crisis radar and post-mortems, cross-source reputation, share-of-voice, creator vetting, multi-engine AI consensus answers, and video/app/product intelligence. Each composite emits a per-leg transparency array; pricing is flat or metered per recipe — run action \"List pricing\" for the exact band.",
  },
  {
    slug: "content_analysis",
    name: "Content Analysis",
    endpointCount: 10,
    social: false,
    description:
      "Cross-web brand-mention search and 6-axis sentiment intelligence over news, blogs, ecommerce, and message boards — paginated mention feeds, sentiment/summary aggregates, rating distributions, phrase and category trends, plus languages/locations/categories/filters reference data.",
  },
  {
    slug: "on_page",
    name: "On-Page",
    endpointCount: 1,
    social: false,
    category: "utility",
    description:
      "On-page SEO audit for a single URL — the technical, content and metadata checks a crawler would run, in one call.",
  },
  {
    slug: "jobs",
    name: "Jobs",
    endpointCount: 11,
    social: false,
    category: "utility",
    description:
      "Cross-board job data — job search and single-listing lookups on LinkedIn, Indeed, Bing and Xing, LinkedIn organization-id resolution, job-title suggestions, and salary ranges by title and country.",
  },
  {
    slug: "us_congress_trades",
    name: "US Congress Trades",
    endpointCount: 19,
    social: false,
    category: "utility",
    description:
      "US Congress stock-trade disclosures (STOCK Act filings) — searchable trades, 48-hour and 7-day recency feeds, the roster of disclosing members, per-politician and per-ticker trading summaries and trade lists, state-delegation trades, and a full stats suite: party comparison, sector and issuer breakdowns, most-active traders and tickers, volume over time, unusual activity, buy/sell ratio, and a late-filing (reporting-gap) ranking.",
  },
];
